id = "vibrant-abyss"
name = "Vibrant Abyss"
version = "0.4.12"
schema_version = 1
authors = [ "Noel Horv√°th <noelhorvath69@gmail.com>" ]
description = "A high-contrast pitch black theme based on the original for Visual Studio Code."
repository = "https://github.com/noelhorvath/vibrant-abyss-zed"
